server:
  port: 8082

spring:
  application:
    name: svarbnetics-api

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
