server:
  port: 8082

spring:
  application:
    name: svarbnetics-api

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

logging:
  level:
    org.mybatis: TRACE
    org.svarb.svarbneticsapi.mapper.OrganismMapper: TRACE
    org.svarb.svarbneticsapi.mapper.ChromosomeMapper: TRACE

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.svarb.svarbneticsapi.model
